### ISSUE TITLE
`install` script missing

### ISSUE THREAD

**Issue by Marin-Kitagawa** [Darkkal44/Cozytile#1]
Hi Darkkal,
I love your `Qtile` design. I wanted to try it out and hence followed the steps. But the `install` script is missing. As I can see from the commit fb2bb8c, you have removed the dotfiles as you are still working on it. I'd love to try this. This is really good

**Comment by Darkkal44** [comment]
Thanks  a ton for admiring my work, I had removed my dots sometime ago only because I had so much more to add and clean up. It'll be back today itself!!
