### ISSUE TITLE
Delay response issue

### ISSUE THREAD

**Issue by AikaAkiyama** [Darkkal44/Cozytile#10]
I'm not sure how to exactly describe it but on the theme Natura and Everforest, I get this weird delay I can't click on anything and I can't see any windows properly. But if I use the other two themes it works fine, but there are a bunch of terminal errors, and the theme isn't applied correctly. I am using a VM so I am not sure if that's the reason, or maybe I messed up on a step perhaps. But I can't figure out anyway to fix it.

**Comment by Darkkal44** [comment]
Both these themes are monochromatic, and some of the stuff in this rice are themed automatically by a utility called pywal, and on the first run, pywal takes a bit of time (1-2min) to grab the colors, so what you have to do is, wait in that black void screen for a min or so.. and you have to wait longer only for the first run.

**Comment by AikaAkiyama** [comment]
Thought maybe that was the case, thank you very much for the response! New to pywal and tiling WM's overall.

**Comment by Darkkal44** [comment]
Fair, you will get used to those soon! And hope it's fixed now 🤝
