### ISSUE TITLE
The last window does not disappear 

### ISSUE THREAD

**Issue by iCrwx** [Darkkal44/Cozytile#11]
I used the automatic installer on a newly installed Arch Linux operating system, when I start qtile (wayland) it doesn't start so I start qtile but things don't disappear, the display manager It is still visible, but very bugged with the bar and when I open anything like a terminal and close it, it closes but does not disappear, I will show a couple of photos so you can see how it looks

![IMG_20230630_181321](https://github.com/Darkkal44/Cozytile/assets/100317382/be8b2711-95e7-435c-bc2f-6ba9ee2f45d7)
![IMG_20230630_181332](https://github.com/Darkkal44/Cozytile/assets/100317382/10d7722f-d666-48f9-ae12-738ef4c341b2)
![IMG_20230630_182110](https://github.com/Darkkal44/Cozytile/assets/100317382/0b0f3ad7-e94b-495c-81d6-6ef17b19ea87)

**Comment by Darkkal44** [comment]
Great to hear that the installer works, Actually this is not supposed to work in qtile Wayland, Wayland doesn't support a ton of stuff like rofi, so never expect it to work with a Wayland environment. 
Now the issue you are facing is most probably because of picom, and in order to fix this, try restarting the system, and wait for atleast 5mins after you put in your passwd and enters the Qtile wm.. this should most probably fix the issue on its own.
Now if you wonder why this is happening, it's because, some parts of the rice is being themed bt pywal, and for the first launch pywal takes some time to read colors from the wallpaper and you just have to give it some time. From the next time you launch/restart your system/qtile you will get it done within 20 seconds or so.
Lemme know if a re-start and some patience does the job.

**Comment by iCrwx** [comment]
> Great to hear that the installer works, Actually this is not supposed to work in qtile Wayland, Wayland doesn't support a ton of stuff like rofi, so never expect it to work with a Wayland environment. 
> Now the issue you are facing is most probably because of picom, and in order to fix this, try restarting the system, and wait for atleast 5mins after you put in your passwd and enters the Qtile wm.. this should most probably fix the issue on its own.
> Now if you wonder why this is happening, it's because, some parts of the rice is being themed bt pywal, and for the first launch pywal takes some time to read colors from the wallpaper and you just have to give it some time. From the next time you launch/restart your system/qtile you will get it done within 20 seconds or so.
> Lemme know if a re-start and a bit of patience does the job. 
> 

Thank you very much for answering, and how do I change the themes?

**Comment by iCrwx** [comment]
> Great to hear that the installer works, Actually this is not supposed to work in qtile Wayland, Wayland doesn't support a ton of stuff like rofi, so never expect it to work with a Wayland environment. 
> Now the issue you are facing is most probably because of picom, and in order to fix this, try restarting the system, and wait for atleast 5mins after you put in your passwd and enters the Qtile wm.. this should most probably fix the issue on its own.
> Now if you wonder why this is happening, it's because, some parts of the rice is being themed bt pywal, and for the first launch pywal takes some time to read colors from the wallpaper and you just have to give it some time. From the next time you launch/restart your system/qtile you will get it done within 20 seconds or so.
> Lemme know if a re-start and a bit of patience does the job. 
> 

Thank you very much for answering, and how do I change the themes?

**Comment by iCrwx** [comment]
> Great to hear that the installer works, Actually this is not supposed to work in qtile Wayland, Wayland doesn't support a ton of stuff like rofi, so never expect it to work with a Wayland environment. 
> Now the issue you are facing is most probably because of picom, and in order to fix this, try restarting the system, and wait for atleast 5mins after you put in your passwd and enters the Qtile wm.. this should most probably fix the issue on its own.
> Now if you wonder why this is happening, it's because, some parts of the rice is being themed bt pywal, and for the first launch pywal takes some time to read colors from the wallpaper and you just have to give it some time. From the next time you launch/restart your system/qtile you will get it done within 20 seconds or so.
> Lemme know if a re-start and a bit of patience does the job. 
> 

I tried what you told me and it didn't work for me, it keeps coming out as before
![IMG_20230630_205609.jpg](https://github.com/Darkkal44/Cozytile/assets/100317382/45208f06-a4ad-4203-bc30-b14abf74fe7c)

**Comment by chadcat7** [comment]
1. picom is not for wayland @Darkkal44!
2. Most probably your system is not compatible with wayland @iCrwx

**Comment by Darkkal44** [comment]
> 1. picom is not for wayland @Darkkal44!
> 
>     2. Most probably your system is not compatible with wayland @iCrwx

Indeed it's not, and I have said it to him that Wayland is not compatible with this rice..

**Comment by Darkkal44** [comment]
@iCrwx oh, that's unfortunate, try this tho.
Do the same thing again, wait for a bit and when the mouse cursor appears, click `windows (command) + T`, this will bring up the theme menu, select Sakura and then patiently wait for 2mins so that the script configures everything as it's for the first time, and now restart the system and wait sometime to see if it works.

**Comment by Darkkal44** [comment]
![IMG_20230630_205609.jpg](https://user-images.githubusercontent.com/100317382/250217244-45208f06-a4ad-4203-bc30-b14abf74fe7c.jpg)

I FEEL LIKE YOU JUST HAVE TO WAIT A BIT MORE IN THIS SCREEN.  that's how it's supposed to work, anyways, If this is not working then try the method I have suggested just before this.

**Comment by iCrwx** [comment]
@Darkkal44 @chadcat7 
Sorry for being such a problem but none of the things you told me worked for me

**Comment by iCrwx** [comment]
@Darkkal44 @chadcat7 
Sorry for being such a problem but none of the things you told me worked for me

**Comment by chadcat7** [comment]
> @Darkkal44 @chadcat7 
> Sorry for being such a problem but none of the things you told me worked for me

Try x11, does it work there? Then we'll see what the issue is on Wayland

**Comment by Darkkal44** [comment]
> @Darkkal44 @chadcat7 Sorry for being such a problem but none of the things you told me worked for me

It's fine, you told me that you're able to launch terminal right? Can you share the qtile log (last few lines) located at  `~/.local/share/qtile/qtile.log`

**Comment by Darkkal44** [comment]
And if you can, then contact me through discord @darkkal44

**Comment by iCrwx** [comment]
> > @Darkkal44 @chadcat7 Sorry for being such a problem but none of the things you told me worked for me
> 
> It's fine, you told me that you're able to launch terminal right? Can you share the qtile log (last few lines) located at  `~/.local/share/qtile/qtile.log`

`FileNotFoundError: [Errno 2] No such file or directory: '~/.config/qtile/autostart_once.sh'2023-86-30 17:35:07,093 WARNING Libqtile Lifecycle.py:_atexit():L37 Qtile will now terminate2023-06-30 17:36:54,501 WARNING Libqtile lifecycle.py:_atexit():L37 Qtile will now terminate2823-86-30 17:50:02,731 ERROR Libqtile core.py:init_():L103 not starting; existing window manager L630`

**Comment by volodymyr-havryliuk165** [comment]
changing
```python
@hook.subscribe.startup_once
def autostart_once():
    subprocess.run('~/.config/qtile/autostart_once.sh')# path to my script, under my user directory
    subprocess.call([home])
```
to
```python
@hook.subscribe.startup_once
def autostart_once():
    home = os.path.expanduser('~/.config/qtile/autostart_once.sh')# path to my script, under my user directory
    subprocess.call([home])
```
worked for me
"windows not disappearing" was caused by wallpaper absence as it seems

**Comment by Darkkal44** [comment]
> changing
> 
> ```python
> @hook.subscribe.startup_once
> def autostart_once():
>     subprocess.run('~/.config/qtile/autostart_once.sh')# path to my script, under my user directory
>     subprocess.call([home])
> ```
> 
> to
> 
> ```python
> @hook.subscribe.startup_once
> def autostart_once():
>     home = os.path.expanduser('~/.config/qtile/autostart_once.sh')# path to my script, under my user directory
>     subprocess.call([home])
> ```
> 
> worked for me "windows not disappearing" was caused by wallpaper absence as it seems

Thanks a lot to you for coming up with a fix, so much appreciated tbh.
I have been busy lately and havnt been able to troubleshoot this..

**Comment by Darkkal44** [comment]
And if I'm not mistaken, every wallpaper seems to be in there and it's provided in the script correctly. And I think this is more likely to be an issue with qtile figuring out where exactly the autostart file is located.. the logs shared by @iCrwx shows the same error...

**Comment by volodymyr-havryliuk165** [comment]
> And if I'm not mistaken, every wallpaper seems to be in there and it's provided in the script correctly. And I think this is more likely to be an issue with qtile figuring out where exactly the autostart file is located.. the logs shared by @iCrwx shows the same error...

I don't really know python but from what i've read, it treats `~` as literal tilde, and to make tilde into `home` you need to expand it with `os.path.expanduser`
However in qtile widgets like Image you don't need to do it because its done under the hood
```python 
# From source code
class Image(base._Widget, base.MarginMixin):
    #bunch of stuff
    def _update_image(self):
        self.img = None

        if not self.filename:
            logger.warning("Image filename not set!")
            return

        self.filename = os.path.expanduser(self.filename)
    #bunch of stuff
```

**Comment by Darkkal44** [comment]
> > And if I'm not mistaken, every wallpaper seems to be in there and it's provided in the script correctly. And I think this is more likely to be an issue with qtile figuring out where exactly the autostart file is located.. the logs shared by @iCrwx shows the same error...
> 
> I don't really know python but from what i've read, it treats `~` as literal tilde, and to make tilde into `home` you need to expand it with `os.path.expanduser` However in qtile widgets like Image you don't need to do it because its done under the hood
> 
> ```python
> # From source code
> class Image(base._Widget, base.MarginMixin):
>     #bunch of stuff
>     def _update_image(self):
>         self.img = None
> 
>         if not self.filename:
>             logger.warning("Image filename not set!")
>             return
> 
>         self.filename = os.path.expanduser(self.filename)
>     #bunch of stuff
> ```

Oh okay, thanks for this information, I too am new to python and ricing in general tbh, and it's wierd how some part of the config works.. now it makes sense why it's showing errors for some people, thanks a lot for your guidance mate.
