### ISSUE TITLE
Installation unusable, everything frozen and popping in and out of existence

### ISSUE THREAD

**Issue by therealmudflap** [Darkkal44/Cozytile#22]
I used archinstall to install my OS, I haven't tried a manual installation yet. When I run the Cozytile install script everything installs fine seemingly but as soon as the system reboots, I log in and nothing appears, if I try to open a terminal suddenly the panel appears but everything is frozen, moving my mouse makes it disappear again and sometimes reappear. I got a terminal to appear on one try but there was no prompt. I am using Xorg. I've not tried this outside of an archinstall installation yet if that matters. my installation was completely untouched, only git had been installed and then Cozytile.
If I need to share any specific log files or any other information let me know, its been a while since I've done much like this so I forget. I can still access my system through a tty and sddm itself seems to work as normal, I just can't use qtile anymore after the installation.

**Comment by therealmudflap** [comment]
Disabling Picom made it so that everything but the terminal itself works. It will appear but nothing is visible until I open another window, it still accepts input. I apologize if this is an easy issue to fix or is completely my fault, I don't know much about this ricing stuff.

**Comment by Darkkal44** [comment]
> I used archinstall to install my OS, I haven't tried a manual installation yet. When I run the Cozytile install script everything installs fine seemingly but as soon as the system reboots, I log in and nothing appears, if I try to open a terminal suddenly the panel appears but everything is frozen, moving my mouse makes it disappear again and sometimes reappear. I got a terminal to appear on one try but there was no prompt. I am using Xorg. I've not tried this outside of an archinstall installation yet if that matters. my installation was completely untouched, only git had been installed and then Cozytile.
> If I need to share any specific log files or any other information let me know, its been a while since I've done much like this so I forget. I can still access my system through a tty and sddm itself seems to work as normal, I just can't use qtile anymore after the installation. 

Are you trying this out in a vm?

**Comment by Darkkal44** [comment]
> Disabling Picom made it so that everything but the terminal itself works. It will appear but nothing is visible until I open another window, it still accepts input. I apologize if this is an easy issue to fix or is completely my fault, I don't know much about this ricing stuff.

No worries, If its getting fixed when u disable picom then the issue is most probably with 3d acceleration being disabled. Please let me know if this setting is enabled/disabled in your vm settings (assuming that you're using a vm)
![image](https://github.com/user-attachments/assets/4b30135b-96e3-45c0-82ec-16001d30d074)

**Comment by therealmudflap** [comment]
> Are you trying this out in a vm?

Originally no, I had tried it on an old spare laptop and the issue came about. I had the same issue on a VM and that solution did it for me, thank you!
I just installed it on a different spare computer and it didn't have any issues this time, so I suppose it's an issue related to the laptop itself? Either way I got it working on a computer which was my original goal in the first place. Thank you for your time and your help, and nice work on the rice, it looks beautiful!

**Comment by Darkkal44** [comment]
> > Are you trying this out in a vm?
> 
> Originally no, I had tried it on an old spare laptop and the issue came about. I had the same issue on a VM and that solution did it for me, thank you!
> I just installed it on a different spare computer and it didn't have any issues this time, so I suppose it's an issue related to the laptop itself? Either way I got it working on a computer which was my original goal in the first place. Thank you for your time and your help, and nice work on the rice, it looks beautiful!

Thanks a ton for the appreciation, I really am curious if there's something like 3d acceleration in the bios of that old laptop lol, maybe it is because of the graphic drivers, im not sure.
Great to know that it works now. And out of curiosity, did it work without any issues in the computer?

**Comment by therealmudflap** [comment]
> Thanks a ton for the appreciation, I really am curious if there's something like 3d acceleration in the bios of that old laptop lol, maybe it is because of the graphic drivers, im not sure. Great to know that it works now. And out of curiosity, did it work without any issues in the computer?

Nothing in bios no, I guess something about the laptop just isn't compatible but oh well. It didn't have any issues at all on the computer, right after the install it worked perfectly.
