### ISSUE TITLE
Cozy and Everforest Themes not working

### ISSUE THREAD

**Issue by martiam** [Darkkal44/Cozytile#4]
Hello, I followed your automatic install instructions, and everything seems to work except the Cozy and Everforest Themes. I also noticed, that there are only 2 items in the `.themes` folder.

**Comment by martiam** [comment]
Changing these to the aforementioned `os.path.expanduser` like in the working configs worked. Also, I assume that the files in the `.themes` folder are your VSCode configs, but they are pathed absolutely to your home folder.

**Comment by martiam** [comment]
Sorry, for the spam, but the Everforest was okay, I just needed to give it some time to load.

**Comment by Darkkal44** [comment]
> I think I found the issue. It's in the `Themes` folder in the home directory. I went through the themes which don't work and turns out their qtile config.py file uses your absolute path `/home/unreal/.config/qtile/autostart_once.sh` instead of using the `os.path.expanduser`

Thanks alot for reminding me that one of the config is hard-coded with my username, I will fix it.

**Comment by Darkkal44** [comment]
> Changing these to the aforementioned `os.path.expanduser` like in the working configs worked. Also, I assume that the files in the `.themes` folder are your VSCode configs, but they are pathed absolutely to your home folder.

As I mentioned above, the gtk themes in .themes directory is completely wip

**Comment by Darkkal44** [comment]
@martiam I've corrected the path for the autostart script, so everything should work properly now. I'm still working on the GTK themes, and I'll update them as soon as they're finished.
