### ISSUE TITLE
Themes are not changed automatically

### ISSUE THREAD

**Issue by mactronmedia** [Darkkal44/Cozytile#5]
I have installed it on my Arch-based distro manuly. Everything works fine, except that the paywall colors and themes are not changed automatically.

Do I need to add any special privileges to rofi scripts?

Thanks!

**Comment by Darkkal44** [comment]
First of all, I'd ask you to update the dotfiles as lately I made a fix in the config files which was causing the issue.
And you will have to wait 50-60 seconds for pywal to set up colors for everforest and Natura theme as their colorscheme is pretty monochromatic. (you have to wait for about a minute only for the first time you change the theme, from then on, it does it in about 5-10 seconds!)
So, the be patient and see if it works now. 
Lmk if its fixed!
