### ISSUE TITLE
Change to dark theme

### ISSUE THREAD

**Issue by BugOrFeature** [Darkkal44/Cozytile#6]
After switching to cozytile sakura (love it by the way!) I'm unable to change the colorscheme of windows to dark (using KDE system setting). Every window is white (firefox, etc). How do I change this? I looked through the qtile config aswell but didn't see anything related to window color at the first glance.

**Comment by BugOrFeature** [comment]
After a reboot and update the file manager switched to the right color scheme, firefox did not mirror system preferences, so forcing it to be dark themed fixed it.

**Comment by Darkkal44** [comment]
Thanks alot for fixing it on your own, actually I've no clue how kde works, and I was afraid that I wont be able to help.. great that you fixed it on your own!! I currently donot have a firefox theme, cause it'd be painful to work on a firefox theme for every single theme lol, Kinda busy irl thb.
