### ISSUE TITLE
your installation file have some syntx errors

### ISSUE THREAD

**Issue by Vikash-Singh-Tanwar** [Darkkal44/Cozytile#7]
install.sh file have some synatax error ive fixed it tohugh please review it

**Comment by Darkkal44** [comment]
Thanks a lot for informing me, I will review it as soon as I get free.

**Comment by Darkkal44** [comment]
I tried it yet again, but it works without any issues, for me. Can you please provide a bit more information, like can you provide the line which shows the syntax error.

**Comment by vs66388** [comment]
> I tried it yet again, but it works without any issues, for me. Can you please provide a bit more information, like can you provide the line which shows the syntax error.

ok cause i tried on two system it didnt installed any packages just sddm and enabled it

**Comment by vs66388** [comment]
its fine works in vm mightve been some issue on my side

**Comment by Darkkal44** [comment]
I've tried it on vm's too, and it works just fine, Its definitely an issue on your side. Lemme know if you come up with anything

**Comment by chadcat7** [comment]
> install.sh file have some synatax error ive fixed it tohugh please review it

@vs66388 it is no use of making an issue without giving a good description! just a "hey there is a syntax error" will do no good. @Darkkal44 or I could use a screenshot or some text giving more detailed information! It would also help us to know which OS, and version of bash you are using. And then we could maybe make it work on your end as well

**Comment by vs66388** [comment]
> > install.sh file have some synatax error ive fixed it tohugh please review it
> 
> @vs66388 it is no use of making an issue without giving a good description! just a "hey there is a syntax error" will do no good. @Darkkal44 or I could use a screenshot or some text giving more detailed information! It would also help us to know which OS, and version of bash you are using. And then we could maybe make it work on your end as well

sorry bro i am new to all this stuff imean github and all

**Comment by Darkkal44** [comment]
> > install.sh file have some synatax error ive fixed it tohugh please review it
> 
> @vs66388 it is no use of making an issue without giving a good description! just a "hey there is a syntax error" will do no good. @Darkkal44 or I could use a screenshot or some text giving more detailed information! It would also help us to know which OS, and version of bash you are using. And then we could maybe make it work on your end as well

Indeed

**Comment by Darkkal44** [comment]
> > > install.sh file have some synatax error ive fixed it tohugh please review it
> > 
> > 
> > @vs66388 it is no use of making an issue without giving a good description! just a "hey there is a syntax error" will do no good. @Darkkal44 or I could use a screenshot or some text giving more detailed information! It would also help us to know which OS, and version of bash you are using. And then we could maybe make it work on your end as well
> 
> sorry bro i am new to all this stuff imean github and all

It's fine, if you're still having the issue, provide me with more details so that I can find a fix for ya

**Comment by Darkkal44** [comment]
> > > > > install.sh file have some synatax error ive fixed it tohugh please review it
> > > > 
> > > > 
> > > > @vs66388 it is no use of making an issue without giving a good description! just a "hey there is a syntax error" will do no good. @Darkkal44 or I could use a screenshot or some text giving more detailed information! It would also help us to know which OS, and version of bash you are using. And then we could maybe make it work on your end as well
> > > 
> > > 
> > > sorry bro i am new to all this stuff imean github and all
> > 
> > 
> > It's fine, if you're still having the issue, provide me with more details so that I can find a fix for ya
> 
> what happened was when i used it on minimal install of arch it didnt istalled dependencies like qtile pywall and all didnt copy any configs all it did was install and enable sddm mightve been some issue on my side

I had actually tried it even before I posted the rice and it was working fine, this surely is an issue on your side.

**Comment by chadcat7** [comment]
@vs66388 sorry for pinging you but there is a high chance that paru/yay is not being installed correctly. @Darkkal44 does the script work on a fresh arch install?

**Comment by Darkkal44** [comment]
In fine with pinging, as he got the error again, I will setup a vm and try it asap and will lyk if it shows any errors

**Comment by chadcat7** [comment]
@vs66388 on a fresh arch install, does the script install yay or paru?

**Comment by vs66388** [comment]
> @vs66388 on a fresh arch install, does the script install yay or paru? and just a hint, `git base-devel` are required to make the script work

both were thier like base-devel is installed with drivers and i installed git for paru

**Comment by Darkkal44** [comment]
> @vs66388 on a fresh arch install, does the script install yay or paru? and just a hint, `git base-devel` are required to make the script work

its been so long.. darn it, I'm so darn sad that im unable to fix these or give a lil attention to this project, my final exams are about to hit on next month and then i think i will be free to make a come back.

**Comment by vs66388** [comment]
> > @vs66388 on a fresh arch install, does the script install yay or paru? and just a hint, `git base-devel` are required to make the script work
> 
> its been so long.. darn it, I'm so darn sad that im unable to fix these or give a lil attention to this project, my final exams are about to hit on next month and then i think i will be free to make a come back.  

Damn that took you loooooonnnng bro I know your pain my exams are going on tooo

**Comment by vs66388** [comment]
I'll try to fix in my free time going through your configs it's been quite a while scine I picked up my Linux laptop so

**Comment by Darkkal44** [comment]
Its now up and running!
