### ISSUE TITLE
Is it possible to remake this bar in polybar or eww??

### ISSUE THREAD

**Issue by rew1nter** [Darkkal44/Cozytile#9]
I find this bar absolutely amazing. But I'm on awesome wm and pretty new to tiling :(

**Comment by Darkkal44** [comment]
> I find this bar absolutely amazing. But I'm on awesome wm and pretty new to tiling :(

Mate, tiling is not so scary, I bet, you will get used to it very soon, it might be a bit hard at the start, but you will get along very easily. And qtile does have non-tiling mode. Anyways it's always good to get along with tiling.
